include:
  - project: "wartek-id/tooling/cicd-templates"
    file: "stages.gitlab-ci.yml"
    ref: v3
  - project: "wartek-id/tooling/cicd-templates"
    file: "job-template.gitlab-ci.yml"
    ref: v3

.build-docker:
  extends:
    - .kaniko-template
  tags:
    - ultramem
  variables:
    KANIKO_ARGUMENTS_01: --build-arg GITLAB_AUTH_TOKEN=$CI_JOB_TOKEN
    KANIKO_ARGUMENTS_03: --build-arg VERSION=$CI_COMMIT_SHA
    KANIKO_ARGUMENTS_06: --cache-ttl=12h
    KANIKO_ARGUMENTS_07: --cache=true
    KANIKO_ARGUMENTS_08: --cache-copy-layers=true
    KANIKO_ARGUMENTS_COMPRESSED_CACHING: --compressed-caching=false
    KANIKO_ARGUMENTS_SNAPSHOT_MODE: --snapshot-mode=redo
    DOCKERFILE: Dockerfile
    IMAGE_REPO: $CI_REGISTRY/kratos-selfservice-ui-node
    DISABLE_CACHE: "true"

docker-build:
  stage: build
  extends:
    - .build-docker